export const allMoviesData = [
            // Latest Releases
            { id: 'sky-utopia-2023', category: 'latestReleases', title: 'Doraemon: Sky Utopia (2023)', description: 'Nobita and Doraemon embark on a grand adventure for a sky utopia.', imageUrl: 'images/doraemon-sky-utopia.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/3932224157088366/', language: 'Hindi' },
            { id: 'stand-by-me-2-2020', category: 'latestReleases', title: 'Doraemon: Stand by Me 2 (2020)', description: 'A heartwarming sequel on Nobita\'s journey to his future wedding.', imageUrl: 'images/doraemon-stand-by-me-2.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/4111010009177962/', language: 'Hindi' },
            { id: 'db-super-hero-2022', category: 'latestReleases', title: 'DB Super: Super Hero (2022)', description: 'The Red Ribbon Army returns, forcing heroes to step up.', imageUrl: 'images/dragon-ball-super-hero.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1882284009295582/', language: 'Hindi' },
            
            // Doraemon Classics (Titles updated with "Doraemon: ")
            { id: 'animal-planet', category: 'doraemonClassics', title: 'Doraemon: Nobita and the Animal Planet', description: 'Nobita and his friends travel to a planet of animal-like beings and help them fight against a threat from outer space.', imageUrl: 'images/doraemon-animal-planet.jpg', videoUrl: 'https://www.facebook.com/reel/795227026821012/', language: 'Hindi' },
            { id: 'treasure-island', category: 'doraemonClassics', title: 'Doraemon: Nobita\'s Treasure Island', description: 'Nobita and Doraemon seek a mysterious treasure island.', imageUrl: 'images/doraemon-treasure-island.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/640454295760593/', language: 'Hindi' },
            { id: 'nayi-duniya', category: 'doraemonClassics', title: 'Doraemon: Nobita Ki Nayi Duniya', description: 'Nobita and Doraemon explore a world of wonders.', imageUrl: 'images/doraemon-nayi-duniya.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/641767961811897/', language: 'Hindi' },
            { id: 'dorabian-nights', category: 'doraemonClassics', title: 'Doraemon: Nobita\'s Dorabian Nights', description: 'Swept into the magical world of Arabian Nights.', imageUrl: 'images/doraemon-dorabian-nights.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/733719062768636/', language: 'Hindi' },
            { id: 'toofani-adventure', category: 'doraemonClassics', title: 'Doraemon: Toofani Adventure', description: 'Doraemon and friends face a storm of challenges.', imageUrl: 'images/doraemon-toofani-adventure.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1677849806264181/', language: 'Hindi' },
            { id: 'jadooi-tapu', category: 'doraemonClassics', title: 'Doraemon: Nobita Aur Jadooi Tapu', description: 'Nobita and Doraemon discover a magical island.', imageUrl: 'images/doraemon-jadooi-tapu.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1044495797465981/', language: 'Hindi' },
            { id: 'moon-exploration', category: 'doraemonClassics', title: 'Doraemon: Moon Exploration', description: 'A fantastic journey to the moon awaits.', imageUrl: 'images/doraemon-moon-exploration.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1089875305836794/', language: 'Hindi' },
            { id: 'undersea-devil', category: 'doraemonClassics', title: 'Doraemon: Undersea Devil', description: 'Doraemon and friends explore an ancient underwater castle.', imageUrl: 'images/doraemon-undersea-devil.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/614771978339141/', language: 'Hindi' },
            { id: 'antarctic-kachi-kochi', category: 'doraemonClassics', title: 'Doraemon: Antarctic Kachi Kochi', description: 'A freezing adventure to uncover a hidden city of ice!', imageUrl: 'images/doraemon-antarctic-kachi-kochi.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1723058328351545/', language: 'Hindi' },
            { id: 'steel-troops', category: 'doraemonClassics', title: 'Doraemon: Steel Troops', description: 'Nobita and Doraemon face a robot invasion to protect Earth.', imageUrl: 'images/doraemon-steel-troops.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1051273367116965/', language: 'Hindi' },
            { id: 'gadget-museum', category: 'doraemonClassics', title: 'Doraemon: Gadget Museum', description: 'A thrilling mystery at the secret gadget museum.', imageUrl: 'images/doraemon-gadget-museum.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1470419020634494/', language: 'Hindi' },
            { id: 'little-space-war', category: 'doraemonClassics', title: 'Doraemon: Little Space War', description: 'Nobita and friends help a tiny alien save his planet.', imageUrl: 'images/doraemon-little-space-war.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1803317223873586/', language: 'Hindi' },
            { id: 'birdopia-sultan', category: 'doraemonClassics', title: 'Doraemon: Birdopia Sultan', description: 'Doraemon and friends help bird-people against an evil ruler.', imageUrl: 'images/doraemon-birdopia-sultan.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/4061355814138236/', language: 'Hindi' },
            { id: 'birth-of-japan', category: 'doraemonClassics', title: 'Doraemon: Birth Of Japan', description: 'Nobita and friends travel to the Stone Age.', imageUrl: 'images/doraemon-birth-of-japan.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1655457565117495/', language: 'Hindi' },
            { id: 'galaxy-super-express', category: 'doraemonClassics', title: 'Doraemon: Galaxy Super Express', description: 'An exciting space adventure across the universe!', imageUrl: 'images/doraemon-galaxy-super-express.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/182637258357201/', language: 'Hindi' },
            { id: 'magical-swordsmen', category: 'doraemonClassics', title: 'Doraemon: Magical Swordsmen', description: 'Nobita and friends become legendary swordsmen in a dream world.', imageUrl: 'images/doraemon-three-magical-swordsmen.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1805560470314218/', language: 'Hindi' },
            { id: 'jalpari', category: 'doraemonClassics', title: 'Doraemon: Jalpari', description: 'Nobita and Doraemon embark on an underwater quest with a mermaid.', imageUrl: 'images/doraemon-jalpari.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1050964053530942/', language: 'Hindi' },
            { id: 'hara-hara-planet', category: 'doraemonClassics', title: 'Doraemon: Hara Hara Planet', description: 'Journey to a dangerous, plant-filled planet.', imageUrl: 'images/doraemon-hara-hara-planet.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/24854423730809045/', language: 'Hindi' },
            { id: 'khel-khilona-bhool-bhulaiya', category: 'doraemonClassics', title: 'Doraemon: Nobita Aur Khel Khilona Bhool Bhulaiya', description: 'Doraemon and Nobita find themselves in a world of toys and must navigate a mysterious and challenging labyrinth.', imageUrl: 'images/doraemon-khel-khilona-bhool-bhulaiya.jpg', videoUrl: 'https://www.facebook.com/reel/1265152048663449/', language: 'Hindi' },
            
            // Other Anime Movies
            { id: 'death-note-relight-2007', category: 'otherAnimeMovies', title: 'Death Note: Visions of God', description: 'A recap film of the original anime, L\'s perspective.', imageUrl: 'images/death-note-relight.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1266322374949691/', language: 'English' },
            { id: 'dbz-battle-of-gods-2013', category: 'otherAnimeMovies', title: 'DBZ: Battle of Gods (2013)', description: 'Goku faces God of Destruction Beerus in a universe-threatening battle.', imageUrl: 'images/dragon-ball-battle-of-gods.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/2608678586139750/', language: 'Hindi' },
            { id: 'db-super-broly-2018', category: 'otherAnimeMovies', title: 'DB Super: Broly (2018)', description: 'Goku and Vegeta face formidable Saiyan warrior Broly.', imageUrl: 'images/dragon-ball-super-broly.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1272086881027408/', language: 'Hindi' },
            { id: 'db-super-super-hero-2022-other', category: 'otherAnimeMovies', title: 'DB Super: Super Hero (2.022)', description: 'Red Ribbon Army returns; Piccolo and Gohan step up.', imageUrl: 'images/dragon-ball-super-hero.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1882284009295582/', language: 'Hindi' }
        ];