export const allMoviesData = [
    // Latest Releases
    { id: 'the-girl-who-leapt-2006', type: 'movie', category: ['latestReleases', 'otherAnimeMovies'], title: 'The Girl Who Leapt Through Time (2006)', description: 'A high-school girl, Makoto Konno, discovers she can time-travel and uses the ability for her own benefit, only to realize her actions have unforeseen consequences for others.', imageUrl: 'images/the-girl-who-leapt-through-time.jpg', videoUrl: 'https://www.facebook.com/reel/836863325760939/', language: 'Japanese (English Subtitle)' },

    { id: 'db-super-hero-2022', type: 'movie', category: ['latestReleases', 'otherAnimeMovies'], title: 'DB Super: Super Hero (2022)', description: 'The Red Ribbon Army returns, forcing heroes to step up.', imageUrl: 'images/dragon-ball-super-hero.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1882284009295582/', language: 'Hindi' },


    // Series
    {
        id: 'demon-slayer-s1',
        type: 'series',
        category: ['latestReleases', 'otherAnimeMovies'],
        title: 'Demon Slayer: Kimetsu no Yaiba',
        description: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
        imageUrl: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
        language: 'Japanese (English Sub)',
        seasons: [
            {
                seasonNumber: 1,
                title: "Unwavering Resolve Arc",
                episodes: [
                    { episodeNumber: 1, title: 'Cruelty', videoUrl: 'https://www.facebook.com/watch/?v=123456', description: 'Tanjiro returns home to find his family slaughtered.' },
                    { episodeNumber: 2, title: 'Trainer Sakonji Urokodaki', videoUrl: 'https://www.facebook.com/watch/?v=123457', description: 'Tanjiro meets a demon slayer trainer.' }
                ]
            },
            {
                seasonNumber: 2,
                title: "Mugen Train Arc",
                episodes: [
                    { episodeNumber: 1, title: 'Flame Hashira Kyojuro Rengoku', videoUrl: 'https://www.facebook.com/watch/?v=123458', description: 'Rengoku investigates a demon presence.' }
                ]
            }
        ]
    },
    {
        id: 'doraemon-2005-series',
        type: 'series',
        category: ['tvSeries'],
        title: 'Doraemon (2005)',
        description: 'Doraemon, a cat robot from the 22nd century, is sent to help Nobita Nobi, a young boy who scores poor grades and is frequently bullied by his two classmates, Gian and Suneo.',
        imageUrl: 'images/doraemon_hero.png',
        language: 'Hindi',
        seasons: [
            {
                seasonNumber: 12,
                title: "Season 12",
                episodes: [
                    { episodeNumber: 1, title: 'The Fishing Pond in My Study Room / Remember! The Excitement of That Day', videoUrl: '', description: 'Doraemon creates a fishing pond in Nobita\'s room. / Nobita revisits a cherished memory from his past.' },
                    { episodeNumber: 2, title: 'The Time Machine is Lost', videoUrl: '', description: 'The time machine disappears, stranding Doraemon and Nobita in the past.' },
                    { episodeNumber: 3, title: 'Slow Down! Hurry Up! / Noby’s Wife', videoUrl: '', description: 'Nobita uses a gadget to alter time perception. / Nobita travels to the future to see who his wife is.' },
                    { episodeNumber: 4, title: 'The Dictator Switch', videoUrl: '', description: 'Nobita uses a terrifying gadget that can erase people from existence with a button press.' },
                    { episodeNumber: 5, title: 'The Stupersonic Verminator / The Almighty Pass', videoUrl: '', description: 'A gadget to exterminate pests goes wrong. / Nobita gets a pass that allows him to enter any place for free.' },
                    { episodeNumber: 6, title: 'The Time Cloth / The Dandelion That Flew Away in the Sky', videoUrl: '', description: 'Doraemon introduces the Time Cloth that can age or restore objects. / The touching story of a dandelion seeking its place.' },
                    { episodeNumber: 7, title: 'Top Secret Spy Operation / Hello, Alien', videoUrl: '', description: 'Nobita plays perilous spy games. / A small alien lands in Nobita\'s room and he tries to safely send it home.' },
                    { episodeNumber: 8, title: 'Nobita’s Underground Country', videoUrl: '', description: 'Nobita builds a secret civilization underground to escape his daily troubles.' },
                    { episodeNumber: 9, title: 'The Switching Rope / Cartoonist Jaiko', videoUrl: '', description: 'A rope that swaps bodies. / Doraemon helps Gian\'s sister Jaiko with her manga career.' },
                    { episodeNumber: 10, title: 'Doraemon’s Everywhere / Heart Cologne', videoUrl: '', description: 'Doraemon seems to be everywhere at once. / A cologne that reveals people\'s true feelings.' },
                    { episodeNumber: 11, title: 'My Love Just Won’t Stop~Meow / Bottle Cap Collection', videoUrl: '', description: 'Doraemon falls in love with a cat. / Nobita becomes obsessed with collecting bottle caps.' },
                    { episodeNumber: 12, title: 'Very, Very Strange Umbrellas / Now-Now Stick', videoUrl: '', description: 'Doraemon shows off unique umbrellas. / A stick that forces people to do things immediately.' },
                    { episodeNumber: 13, title: 'I Got 100%, For Once in My Life / The Cursing Camera', videoUrl: '', description: 'Nobita finally scores a 100% on a test. / A camera that makes Voodoo dolls of people.' },
                    { episodeNumber: 14, title: 'Star Wars in My Attic', videoUrl: '', description: 'A space battle breaks out in Nobita\'s attic using miniaturized gadgets.' },
                    { episodeNumber: 15, title: 'The Transformation Biscuits / Goodbye, Shizuka', videoUrl: '', description: 'Biscuits that transform the eater into animals. / Nobita tries to make Shizuka detest him for her own good.' },
                    { episodeNumber: 16, title: 'The Debut of the Mood Changing Orchestra / The Friend Circle', videoUrl: '', description: 'An orchestra that alters emotions. / A circle that makes anyone inside a best friend.' },
                    { episodeNumber: 17, title: 'Wrestling Killer / The Woodcutter’s Spring', videoUrl: '', description: 'Nobita deals with a hired wrestler. / A spring that upgrades items dropped into it, like the fable.' },
                    { episodeNumber: 18, title: 'Doraemon’s Prediction / The Girl Who is Pure Like a Madonna Lily', videoUrl: '', description: 'Doraemon predicts the future. / Nobita meets a mysterious, beautiful girl.' },
                    { episodeNumber: 19, title: 'Shadow Hunting / The Memory Bread', videoUrl: '', description: 'Nobita\'s shadow comes to life. / Bread that allows you to memorize anything written on it.' },
                    { episodeNumber: 20, title: 'Antique Wars / Ghost Lamp', videoUrl: '', description: 'Competing to find valuable antiques. / A lamp that summons ghosts to scare people.' },
                    { episodeNumber: 21, title: 'Dream Wind Chime / The Change of Clothes Camera', videoUrl: '', description: 'A wind chime that controls dreams. / A camera that instantly changes people\'s outfits.' },
                    { episodeNumber: 22, title: 'Ancestors, Come On', videoUrl: '', description: 'Nobita summons his ancestors to help him.' },
                    { episodeNumber: 23, title: 'The Bowing Grasshoppers / Noby, Li’l G’s Boyfriend', videoUrl: '', description: 'Grasshoppers that make people apologize. / Nobita is mistaken for a girl\'s boyfriend.' },
                    { episodeNumber: 24, title: 'The Guiding Angel / Noby Can’t Find His Way Home', videoUrl: '', description: 'A puppet that guides you to the best outcome. / Nobita gets hopelessly lost.' },
                    { episodeNumber: 25, title: 'I Like You! I Like You! I Like Youuu! / Let’s Put Ace to Sleep', videoUrl: '', description: 'A gadget that amplifies affection. / Putting a rival to sleep to win a challenge.' },
                    { episodeNumber: 26, title: 'The Good Ol’ Days', videoUrl: '', description: 'Visiting the past to experience the "good old days".' },
                    { episodeNumber: 27, title: 'Treasure Planet', videoUrl: '', description: 'A space adventure to find a planet made of treasure.' },
                    { episodeNumber: 28, title: 'Beware! It’s the Lion Mask / Noby Runs Away From Home for a Veeeery Long Time', videoUrl: '', description: 'A scary comic book character comes to life. / Nobita runs away and spends years in the future.' },
                    { episodeNumber: 29, title: 'Honest Taro / The Medusa Head', videoUrl: '', description: 'A doll that speaks the truth brutally. / A monster head that turns people to stone.' },
                    { episodeNumber: 30, title: 'A N-S Emblem', videoUrl: '', description: 'Badges that act like magnets, repelling or attracting people.' },
                    { episodeNumber: 31, title: 'The All Season Badge / Operation Y Candle', videoUrl: '', description: 'Controlling the personal climate. / A candle that makes people do whatever you say.' },
                    { episodeNumber: 32, title: 'Harship Miso / The Invincible Insect Pills', videoUrl: '', description: 'Miso that makes life incredibly difficult. / Pills that give you insect-like abilities.' },
                    { episodeNumber: 33, title: 'I Love You, Roboko / The Voice Thickner', videoUrl: '', description: 'Nobita falls for a robot girl. / Solidifying voice into blocks.' },
                    { episodeNumber: 34, title: 'N-S Badges / The Snail House Sure is Carefree', videoUrl: '', description: 'Magnetic badges cause chaos. / Living effortlessly inside a snail shell.' },
                    { episodeNumber: 35, title: 'Romance in the Snowy Mountain', videoUrl: '', description: 'Nobita tries to woo Shizuka during a blizzard simulation.' },
                    { episodeNumber: 36, title: 'The Big RC Naval Battle', videoUrl: '', description: 'A massive battle using remote-controlled ships to fight a real threat.' },
                    { episodeNumber: 37, title: 'Eight Days in the Place of the Demon King Part 01', videoUrl: '', description: 'Nobita and friends travel to a fantasy world to fight a Demon King.' },
                    { episodeNumber: 38, title: 'Eight Days in the Place of the Demon King Part 02', videoUrl: '', description: 'The conclusion of the epic battle against the Demon King.' },
                    { episodeNumber: 39, title: 'The Smoke Monster of the Lamp / The New Year’s Party in the Wallpaper', videoUrl: '', description: 'A genie-like smoke monster chases Nobita. / A party held inside the world of the wallpaper.' },
                    { episodeNumber: 40, title: 'I’m Going to Transfer this Cold / Hot Spring Trip', videoUrl: '', description: 'Passing a cold to someone else using a gadget. / A relaxing trip to a hot spring.' },
                    { episodeNumber: 41, title: 'The Paddy Field Mat / The Over Exaggerating Overcoat', videoUrl: '', description: 'Growing rice in your room. / A coat that makes every event seem dramatically exaggerated.' },
                    { episodeNumber: 42, title: 'The Illustrated Encyclopedia of Real Things / Creating the Earth', videoUrl: '', description: 'Bringing book illustrations to life. / Nobita creates his own miniature Earth.' },
                    { episodeNumber: 43, title: 'The Progression Regression Beam / The Castaway Story from Long Ago', videoUrl: '', description: 'Advancing or reversing objects\' time. / A story of a castaway from ancient times.' },
                    { episodeNumber: 44, title: 'The Dream Channel / Dinosaur Footprints Discovered', videoUrl: '', description: 'Watching people\'s dreams on TV. / Nobita hunts for dinosaur fossils.' },
                    { episodeNumber: 45, title: 'The Big Papercraft Riot / A Dinosaur is Here!', videoUrl: '', description: 'Papercraft creations run wild. / A dinosaur appears in the neighborhood.' },
                    { episodeNumber: 46, title: 'Oh, Mr. Dinosaur… Please Come to Japan', videoUrl: '', description: 'Nobita tries to bring dinosaurs to Japan.' },
                    { episodeNumber: 47, title: 'Nature Plastic Model Series', videoUrl: '', description: 'Building nature landscapes with plastic models.' },
                    { episodeNumber: 48, title: 'Giant Monster of the Uninhabited Island', videoUrl: '', description: 'Nobita encounters a monster on a deserted island.' },
                    { episodeNumber: 49, title: 'The Word Game Transformation Egg / I’ll Be the King of the Stone Age', videoUrl: '', description: 'Objects transform based on word games. / Nobita travels to the Stone Age to rule.' },
                    { episodeNumber: 50, title: 'The Great Avalanche in My Room / The Big Fossil Discovery', videoUrl: '', description: 'Creating a ski slope in the bedroom. / Digging for fossils.' },
                    { episodeNumber: 51, title: 'Space Tarzan', videoUrl: '', description: 'Nobita becomes a Tarzan figure on an alien planet.' },
                    { episodeNumber: 52, title: 'All the Way From the Country of the Future', videoUrl: '', description: 'A visitor arrives from the 22nd century.' }
                ]
            },
            {
                seasonNumber: 13,
                title: "Season 13",
                episodes: [
                    { episodeNumber: 1, title: "The City of Dreams, Nobita Land / I'm Gonna Become A Fine Dad", videoUrl: '', description: "Creating a miniature city for kids. / Nobita practices parenting with a robot son." },
                    { episodeNumber: 2, title: 'Esper Suneo / Suneo is the Ideal Big Brother', videoUrl: '', description: 'Suneo gains psychic powers? / Suneo tries to be the perfect sibling.' },
                    { episodeNumber: 3, title: 'Even in the Stomach, in the Acid / Pero! Come Back to Life', videoUrl: '', description: 'A journey inside the human body. / Bringing a beloved pet back to life.' },
                    { episodeNumber: 4, title: 'Big Problem With the X-Ray Stickers / The Human Book Cover', videoUrl: '', description: 'Stickers that see through anything. / Turning a person into a book.' },
                    { episodeNumber: 5, title: "Don't Cry, Jaiko / Jaiko's New Comic", videoUrl: '', description: "Helping Jaiko with a heartbreaking story. / Jaiko seeks inspiration for her art." },
                    { episodeNumber: 6, title: "The Lazy Day / Aren't You Nobita, the Cat", videoUrl: '', description: "A gadget to make holidays longer. / Nobita swaps bodies with a cat." },
                    { episodeNumber: 7, title: 'Swapping Moms / Nobita Disappeared', videoUrl: '', description: 'Nobita and friends swap mothers. / Nobita turns invisible and causes trouble.' },
                    { episodeNumber: 8, title: 'All Alone in the City of the Future / The Schedule Clock', videoUrl: '', description: 'Nobita gets stranded in 22nd century Tokyo. / A clock that strictly enforces plans.' },
                    { episodeNumber: 9, title: "I'll Become a Singer By Eating Candy / An Emotional, Heart Touching Expression", videoUrl: '', description: "Candy that makes anyone a great singer. / Learning to express deep emotions." },
                    { episodeNumber: 10, title: 'Memories of Grandma', videoUrl: '', description: 'Nobita travels back in time to visit his kind grandmother.' },
                    { episodeNumber: 11, title: 'The Just As You Said Pills / The World is Full of Lies', videoUrl: '', description: 'Pills that make whatever you say reality. / A world where lies become truth.' },
                    { episodeNumber: 12, title: "Nobita's Castaway Story - Chip Pocket Two Dimensional Camera", videoUrl: '', description: "Surviving on an island with a pocket helper. / A camera that flattens objects." },
                    { episodeNumber: 13, title: 'The Stupidity Time Bomb / The In Advance Diary is Horrible', videoUrl: '', description: 'A bomb that explodes if you act foolishly. / A diary that predicts a bad future.' },
                    { episodeNumber: 14, title: 'Assorted Monsters / Which is a Lie! Our Sale', videoUrl: '', description: 'Summoning classic monsters. / A sale where lies are the currency.' },
                    { episodeNumber: 15, title: 'What Are Those Two Doing, All Alone Together / Water Processing Sprinkle', videoUrl: '', description: 'Spying on a secret meeting. / Turning anything into water.' },
                    { episodeNumber: 16, title: 'The Equality Bomb / Please Save Me', videoUrl: '', description: 'Making everyone equal in ability. / Nobita calls for help in a crisis.' },
                    { episodeNumber: 17, title: 'Watercycline / The Reality Pillow', videoUrl: '', description: 'Transforming water into different shapes. / Dreams on this pillow become real.' },
                    { episodeNumber: 18, title: 'Goodbye, Nobita! Doraemon Goes Back To The Future', videoUrl: '', description: 'Doraemon must return to the 22nd century forever.' },
                    { episodeNumber: 19, title: "Doraemon's Song / Lighter Play", videoUrl: '', description: "Doraemon sings a heartfelt song. / Using a magic lighter for fun." },
                    { episodeNumber: 20, title: 'What! Nobita Got 100 Points / The Devil Card', videoUrl: '', description: 'Nobita unbelievably aces a test. / A card that grants wishes for a price.' },
                    { episodeNumber: 21, title: 'The Light or Heavy Meter / The Strange Encounter Machine', videoUrl: '', description: 'Changing the weight of objects. / A machine that summons strange creatures.' },
                    { episodeNumber: 22, title: 'The Absconding Leaf / God Robot Extends His Hand of Love', videoUrl: '', description: 'A leaf that makes you vanish. / A robot deity that spreads love.' },
                    { episodeNumber: 24, title: 'The Confidence Eliminator / The Bad Luck Diamond', videoUrl: '', description: 'Reviewing a gadget that destroys confidence. / A diamond that brings terrible luck.' },
                    { episodeNumber: 25, title: 'The Fearsome Justice Rope / The Mini Hot Air Balloon', videoUrl: '', description: 'A rope that punishes bad deeds. / Adventure in a tiny balloon.' },
                    { episodeNumber: 26, title: 'The Four Dimensional Building Extension Blocks / The Conclusion Yarn', videoUrl: '', description: 'Adding extra rooms to the house. / A yarn that fast-forwards to the end.' },
                    { episodeNumber: 27, title: 'The Urashima Candy', videoUrl: '', description: 'Candy that makes you age like the legend of Urashima Taro.' },
                    { episodeNumber: 29, title: 'The What If Phone Box / Winning Back Shizuka-Chan Part 01', videoUrl: '', description: 'Creating a world where magic exists. / Nobita fights to win Shizuka\'s heart.' },
                    { episodeNumber: 30, title: 'Winning Back Shizuka-Chan Part 02 / Oh, Lovely Mii-Chan!', videoUrl: '', description: 'The conclusion of Nobita\'s romantic quest. / Doraemon\'s cat crush.' },
                    { episodeNumber: 31, title: 'The Sleeping Genius Nobita / Robinson Crusoe Set', videoUrl: '', description: 'Nobita becomes a genius while asleep? / Surviving on a desert island.' },
                    { episodeNumber: 32, title: "The Lie Speaker / Big Problem! Suneo's Test Paper", videoUrl: '', description: "A beak that makes lies sound true. / Suneo tries to hide a bad grade." },
                    { episodeNumber: 34, title: 'Exploring the Earth Part 01', videoUrl: '', description: 'A journey to uncover the secrets of the planet.' },
                    { episodeNumber: 35, title: 'Exploring the Earth Part 02', videoUrl: '', description: 'Continuing the exploration deep into the Earth.' },
                    { episodeNumber: 36, title: 'A World Without Mirrors', videoUrl: '', description: 'Nobita creates a world where no reflections exist.' },
                    { episodeNumber: 37, title: 'Blind Spot Star', videoUrl: '', description: 'A star that makes you invisible to others\' attention.' },
                    { episodeNumber: 38, title: "There's No Way We Can Produce a Cartoon / Nobita's Black Hole", videoUrl: '', description: "Trying to make an anime episode. / Nobita eats too much and becomes a black hole." },
                    { episodeNumber: 39, title: "Sorcerer Nobita / The Secret of the Devil King's Castle", videoUrl: '', description: "Nobita becomes a wizard. / Exploring a spooky castle." },
                    { episodeNumber: 40, title: 'The Girl With the Red Shoes / The Jaws of the Vacant Lot', videoUrl: '', description: 'A story about a girl from a fairy tale. / A shark appears in the lot?' },
                    { episodeNumber: 41, title: 'Operation Rescue Nobita', videoUrl: '', description: 'Doraemon and friends launch a mission to save Nobita.' },
                    { episodeNumber: 42, title: 'Gratitude Halo / The Person Living Room', videoUrl: '', description: 'A halo that makes everyone grateful to you. / A room that feels like a person.' },
                    { episodeNumber: 43, title: "Magical Girl Shizu-Chan / The Secret of Shizuka-Chan's Heart", videoUrl: '', description: "Shizuka transforms into a magical girl. / Reading Shizuka\'s diary?" },
                    { episodeNumber: 44, title: 'Super Gian, Hero of Justice / Owl Man, Hero of Justice', videoUrl: '', description: 'Gian becomes a superhero? / A nocturnal hero emerges.' },
                    { episodeNumber: 45, title: "Could You Please Adopt Doraemon / The Horrors of Gian's Birthday", videoUrl: '', description: "Nobita tries to give Doraemon away. / Gian\'s birthday concert is coming." },
                    { episodeNumber: 46, title: "The Horrors of Gian's Birthday Return / Gian is Beaten!", videoUrl: '', description: "The concert nightmare continues. / Gian finally loses a fight." },
                    { episodeNumber: 47, title: "Seems Bad but not Spray / I'll Use the Savings I Don't Have", videoUrl: '', description: "Making bad things look good. / Spending future money today." },
                    { episodeNumber: 49, title: 'The Pitch Black Pop Stars / Dramatic Gas', videoUrl: '', description: 'Pop stars in the dark. / Gas that makes life overly dramatic.' },
                    { episodeNumber: 50, title: 'The Forceful Athletic House / A Cat Made a Company, Meow', videoUrl: '', description: 'The house forces you to exercise. / Cats start a business.' },
                    { episodeNumber: 51, title: "The Pool in the Clouds / Scoop! Nobita's Secret Date", videoUrl: '', description: "Swimming in a cloud pool. / Paparazzi catch Nobita on a date." },
                    { episodeNumber: 52, title: 'The Elephant and the Uncle', videoUrl: '', description: 'A touching story about an uncle and an elephant at the zoo.' }
                ]
            },
            {
                seasonNumber: 14,
                title: "Season 14",
                episodes: [
                    { episodeNumber: 1, title: 'Steal Mom’s Diamond Ring / Hungry Master', videoUrl: '', description: 'Nobita travels back in time to retrieve a lost ring. / A master teaches the art of being hungry.' },
                    { episodeNumber: 2, title: 'Be Careful with the Future Shopping / Is Doraemon Seriously Ill', videoUrl: '', description: 'Buying things from the future goes wrong. / Doraemon acts shockingly sick.' },
                    { episodeNumber: 3, title: 'Don’t Take My Jack Away / Nobita Raises Moon Princess', videoUrl: '', description: 'Protecting a jack-in-the-box. / Nobita meets Kaguya-hime on the moon.' },
                    { episodeNumber: 4, title: 'Shopping Sun Wukong, Cleaning Cinderella / Nobita Becomes a Mountain Hermit', videoUrl: '', description: 'Fairy tale characters do chores. / Nobita seeks a simple life in nature.' },
                    { episodeNumber: 5, title: 'Typhoon Fuuko', videoUrl: '', description: 'Nobita befriends a living typhoon named Fuuko.' },
                    { episodeNumber: 6, title: 'Pinocchio’s Flower / The 21st Century Lord', videoUrl: '', description: 'A flower that detects lies. / A feudal lord visits the future.' },
                    { episodeNumber: 7, title: 'The Gourmet Tablecloth / The Abominable Snowman’s Part-time Job', videoUrl: '', description: 'Food appears on demand. / A yeti works a job in the city.' },
                    { episodeNumber: 8, title: 'I’m Mini Doraemon / Looks, Strength or IQ', videoUrl: '', description: 'Mini-Dora causes mischief. / Choosing between beauty, power, or intelligence.' },
                    { episodeNumber: 9, title: 'The Electrifying Trade / The Sweets Farm', videoUrl: '', description: 'Trading items using electricity. / Growing sweets like vegetables in the field.' },
                    { episodeNumber: 10, title: 'Operation, Get Nobita to School On Time / Defeat Gian The Magic Spell', videoUrl: '', description: 'Strategies to be punctual. / A spell to finally beat Gian?' },
                    { episodeNumber: 11, title: 'Nobita + Pigeon = / A Will of Rock', videoUrl: '', description: 'Combining with a pigeon to fly. / Developing an unshakeable will.' },
                    { episodeNumber: 12, title: 'Suneo Goes to a Hairdresser’s / Good-bye, Suneo…', videoUrl: '', description: 'Suneo gets a terrible haircut. / Is Suneo really moving away?' },
                    { episodeNumber: 13, title: 'Space Gunfighter, Nobita', videoUrl: '', description: 'Nobita becomes a hero in a western-style space simulation.' },
                    { episodeNumber: 14, title: 'Cosmo Gunfighter, Nobita', videoUrl: '', description: 'The continuation of Nobita\'s space western adventure.' },
                    { episodeNumber: 15, title: 'Salute to Commander Nobita / Genius Dekisugi’s Rocket Plan', videoUrl: '', description: 'Nobita leads a playful army. / Dekisugi builds a real rocket.' },
                    { episodeNumber: 16, title: 'Invincible, Ultra-special, Mighty, Strong, Super Armor / The Spirit That Loved Nobita', videoUrl: '', description: 'Over-the-top armor for safety. / A snow spirit falls for Nobita.' },
                    { episodeNumber: 17, title: 'The Forest is Alive', videoUrl: '', description: 'The local forest has a heart and consciousness.' },
                    { episodeNumber: 18, title: 'The Day I Was Born', videoUrl: '', description: 'Nobita travels back to see his birth and feel his parents\' love.' },
                    { episodeNumber: 19, title: 'Farewell Test', videoUrl: '', description: 'Nobita studies hard to avoid failing a crucial test.' },
                    { episodeNumber: 20, title: 'Nobita is Shizuka’s Present', videoUrl: '', description: 'Nobita shrinks himself to be Shizuka\'s birthday gift.' },
                    { episodeNumber: 21, title: 'The Decisive Battle of the 22nd Century Doraemon vs Dracula', videoUrl: '', description: 'Doraemon battles a robot vampire in the future.' },
                    { episodeNumber: 22, title: 'The Decisive Battle of the 22nd Century Doraemon vs Dracula (Part 2)', videoUrl: '', description: 'The conclusion of the epic battle against Dracula.' },
                    { episodeNumber: 23, title: 'Nobita, the Bumbling Detective / The Real Game of the Future', videoUrl: '', description: 'The gang plays a mystery solving game. / A hyper-realistic future simulation.' },
                    { episodeNumber: 24, title: 'A Subway for Father’s Day', videoUrl: '', description: 'Doraemon and Nobita build a private subway line for Dad.' },
                    { episodeNumber: 25, title: 'Gian in Love', videoUrl: '', description: 'Gian falls in love and tries to change his ways.' },
                    { episodeNumber: 26, title: 'Space Wars During the Star Festival', videoUrl: '', description: 'A miniature space battle happens on Tanabata.' },
                    { episodeNumber: 27, title: 'My Bodyguard is a Guardian Spirit / Someone Worse Than Me Has Come', videoUrl: '', description: 'A spirit protects Nobita. / A transfer student is even clumsier than Nobita.' },
                    { episodeNumber: 28, title: 'Multiplixir / Goodbye Hana', videoUrl: '', description: 'A potion duplicates items. / Farewell to a beloved zoo elephant named Hana.' },
                    { episodeNumber: 29, title: 'But There Really Is a Ghost', videoUrl: '', description: 'Nobita tries to prove to everyone that ghosts exist.' },
                    { episodeNumber: 30, title: 'Plan Your Birthdays / Redo Life Machine', videoUrl: '', description: 'Planning the perfect party. / A machine to restart your life from a save point.' },
                    { episodeNumber: 31, title: 'Stone-age Hotel', videoUrl: '', description: 'Opening a luxury hotel in the prehistoric era.' },
                    { episodeNumber: 32, title: 'Knockout the Jians', videoUrl: '', description: 'Dealing with multiple clones of Gian.' },
                    { episodeNumber: 33, title: 'Redraw the World / Give a Day-off to Doraemon', videoUrl: '', description: 'Changing reality with a magic pen. / Nobita tries to let Doraemon relax.' },
                    { episodeNumber: 34, title: 'Adventure Tea / Tonguistry Tells it Right', videoUrl: '', description: 'Tea that makes everyday life an adventure. / Palm reading for the tongue.' },
                    { episodeNumber: 35, title: 'Nobita’s 3000 Days on an Uninhabited Island', videoUrl: '', description: 'Nobita runs away and survives on a desert island for years.' },
                    { episodeNumber: 36, title: 'Nobita Robot Is Useless / Nobita’s Girlfriend Catalogue', videoUrl: '', description: 'A robot copy of Nobita is also clumsy. / Browsing potential future girlfriends.' },
                    { episodeNumber: 37, title: 'Can’t Stop Gossiping About Love / Time Move', videoUrl: '', description: 'Gossip spreads uncontrollably with a gadget. / Skipping time to avoid bad moments.' },
                    { episodeNumber: 38, title: 'Then We Went On a Journey', videoUrl: '', description: 'The gang goes on a reflective journey using a gadget.' },
                    { episodeNumber: 39, title: 'Nobita is Admirable Once Again / Suneo’s Invincible Fortress', videoUrl: '', description: 'Nobita tries to be praised. / Suneo builds an impregnable fort.' },
                    { episodeNumber: 40, title: 'Even Cushions Have Souls', videoUrl: '', description: 'A gadget reveals the spirits inside everyday objects.' },
                    { episodeNumber: 41, title: 'Make a Younger Brother / Take the Path of Evil', videoUrl: '', description: 'Creating a sibling gadget. / Nobita tries to be a villain but fails.' },
                    { episodeNumber: 42, title: 'The World’s Best Melon Bread / Dorami’s Worst Day', videoUrl: '', description: 'Hunting for the perfect snack. / Dorami has a terrible luck day.' },
                    { episodeNumber: 43, title: 'We Became Superheroes', videoUrl: '', description: 'The friends use gadgets to become a superhero team.' },
                    { episodeNumber: 44, title: 'We Became Superheroes (Part 2)', videoUrl: '', description: 'The superheroes face a real threat to the town.' },
                    { episodeNumber: 45, title: 'Nobita Became Wolf', videoUrl: '', description: 'Does using a gadget turn Nobita into a werewolf?' },
                    { episodeNumber: 46, title: 'Magician Nobita / The Mysterious Story', videoUrl: '', description: 'Nobita learns magic tricks. / A spooky mystery unfolds.' },
                    { episodeNumber: 47, title: 'The Great Pirate Decisive Battle', videoUrl: '', description: 'Nobita and friends go on a pirate adventure.' },
                    { episodeNumber: 48, title: 'The Great Pirate Decisive Battle (Part 2)', videoUrl: '', description: ' The thrilling conclusion of the pirate saga.' },
                    { episodeNumber: 49, title: 'The Day Doraemon is Reborn', videoUrl: '', description: 'Doraemon gets reset and they must restore his memory.' },
                    { episodeNumber: 50, title: 'Save the Prince! The Legend of Dorami and the Three Swordsmen', videoUrl: '', description: 'Dorami stars in a fantasy adventure to save a prince.' },
                    { episodeNumber: 51, title: 'Hoi of the Donjara Village', videoUrl: '', description: 'Nobita meets a tiny boy named Hoi and helps his village.' },
                    { episodeNumber: 52, title: 'The Dora Dora Space-time Adventure / It’s the Year of the Mouse!', videoUrl: '', description: 'A space-time romp. / Celebrating the zodiac year of the mouse.' },
                ]
            },
            {
                seasonNumber: 15,
                title: "Season 15",
                episodes: [
                    { episodeNumber: 1, title: 'Homemade Giant Robot Goes Wild!', videoUrl: '', description: 'Nobita builds a giant robot that goes completely out of control.' },
                    { episodeNumber: 2, title: 'The Magic Stick / Escape from 0', videoUrl: '', description: 'A stick that grants magic wishes. / Nobita desperately tries to avoid scoring a zero.' },
                    { episodeNumber: 3, title: 'Nobizaemon’s Secret', videoUrl: '', description: 'The gang investigates the mystery of Nobita\'s ancestor, Nobizaemon.' },
                    { episodeNumber: 4, title: 'Nobita’s Fantasy', videoUrl: '', description: 'Nobita uses a gadget to bring his fantasy world to life.' },
                    { episodeNumber: 5, title: 'Half of the Half of the Half / That Day At That Time', videoUrl: '', description: 'A gadget that splits things infinitely. / Traveling back to visit a specific cherished moment.' },
                    { episodeNumber: 6, title: 'Cheerleader’s Glove / Nobita and Shizuka’s House', videoUrl: '', description: 'Gloves that cheer you on to victory. / Nobita and Shizuka play house together.' },
                    { episodeNumber: 7, title: 'Fictitious Animal Safari Park', videoUrl: '', description: 'Visiting a safari park filled with mythical creatures like dragons and unicorns.' },
                    { episodeNumber: 8, title: 'Monster Man from the Future World', videoUrl: '', description: 'A scary looking visitor arrives from the future.' },
                    { episodeNumber: 9, title: 'Welcome to the Center of the Earth – The First Part', videoUrl: '', description: 'The friends start an expedition to reach the center of the Earth.' },
                    { episodeNumber: 10, title: 'Welcome to the Center of the Earth – The Latter Part', videoUrl: '', description: 'The thrilling conclusion of the hollow earth adventure.' },
                    { episodeNumber: 11, title: 'Shizuka Has Disappeared', videoUrl: '', description: 'Shizuka goes missing under mysterious circumstances.' },
                    { episodeNumber: 12, title: 'Nobita’s Proposal Strategy', videoUrl: '', description: 'Nobita travels to the future to ensure his proposal to Shizuka works.' },
                    { episodeNumber: 13, title: 'The Nobi Family Budgets in a Pinch! / Doraemon on a Diet!', videoUrl: '', description: 'The family faces a financial crisis. / Doraemon tries to lose weight.' },
                    { episodeNumber: 14, title: 'Self Mask Ally of Justice', videoUrl: '', description: 'Nobita wears a mask that forces him to be a superhero.' },
                    { episodeNumber: 15, title: 'Friend-making Topknot / Gian the Freeloader', videoUrl: '', description: 'A futuristic hair bun that attracts friends. / Gian decides to live at Nobita\'s house.' },
                    { episodeNumber: 16, title: 'It’s Tough Being the Rain Man the Bringer of Rain', videoUrl: '', description: 'Nobita meets a man who unwittingly brings rain wherever he goes.' },
                    { episodeNumber: 17, title: 'The Upside Down Planet', videoUrl: '', description: 'They visit a planet where everything is the opposite of Earth.' },
                    { episodeNumber: 18, title: 'I Quit Being Doraemon / The Case of Suneo’s Kidnapping', videoUrl: '', description: 'Doraemon goes on strike. / The gang investigates Suneo\'s sudden disappearance.' },
                    { episodeNumber: 19, title: 'Let’s Ride on an Insect Airplane', videoUrl: '', description: 'Shrinking down to pilot real insects like airplanes.' },
                    { episodeNumber: 20, title: 'How to Take a Walk Underwater / Winter Comes During Summer', videoUrl: '', description: 'Gadgets allow walking on the sea floor. / Bringing winter fun to a hot summer day.' },
                    { episodeNumber: 21, title: 'That’s Why a Ghost Appears', videoUrl: '', description: 'Doraemon and Nobita discover the truth behind a local haunting.' },
                    { episodeNumber: 22, title: 'Save Nobita from His Dreams', videoUrl: '', description: 'Doraemon enters Nobita\'s nightmares to save him.' },
                    { episodeNumber: 23, title: 'The Happy Little Mermaid', videoUrl: '', description: 'Nobita befriends a mermaid and tries to help her.' },
                    { episodeNumber: 24, title: 'Doraemon in Love', videoUrl: '', description: 'Doraemon falls head over heels for a cat again.' },
                    { episodeNumber: 25, title: 'Muku the Hopeless Dog / Dwarf Robots are Hard Workers!', videoUrl: '', description: 'Nobita tries to train Gian\'s dog. / Tiny robots work while you sleep.' },
                    { episodeNumber: 26, title: 'There’s Only One Nobita in the World', videoUrl: '', description: 'Nobita learns to appreciate his own unique value.' },
                    { episodeNumber: 27, title: 'Nobita’s Baby Runs Amuck!', videoUrl: '', description: 'Nobita has to babysit a baby that causes endless chaos.' },
                    { episodeNumber: 28, title: 'The Nobi House Becomes a Giant Maze! / Violetta of the Rainbow', videoUrl: '', description: 'A gadget turns the house into a complex labyrinth. / A story about a rainbow girl.' },
                    { episodeNumber: 29, title: 'Farewell To That Window', videoUrl: '', description: 'A touching story about saying goodbye to a window view.' },
                    { episodeNumber: 30, title: 'Faceless Because of an Eraser / Toy Soldiers', videoUrl: '', description: 'A gadget accidentally erases a face. / Toy soldiers come to life to protect Nobita.' },
                    { episodeNumber: 31, title: 'Hot-blooded! Nobita’s Sports Meet', videoUrl: '', description: 'Nobita gets unusually motivated for the school sports day.' },
                    { episodeNumber: 32, title: 'Repel the Aliens!', videoUrl: '', description: 'The gang prepares to defend Earth from an alien invasion (or so they think).' },
                    { episodeNumber: 33, title: 'Gian’s Terrifying Dinner Show / Even Nobita Sometimes Thinks', videoUrl: '', description: 'Gian cooks dinner for his concert audience. / Nobita has a moment of deep philosophical thought.' },
                    { episodeNumber: 34, title: 'Super Dog! Chuken-Pa', videoUrl: '', description: 'A story about a faithful dog named Chuken-Pa.' },
                    { episodeNumber: 35, title: 'Black Hole in Town / What are Gian’s Advantages', videoUrl: '', description: 'A miniature black hole appears. / Nobita tries to list Gian\'s good qualities.' },
                    { episodeNumber: 36, title: 'Long Long First Three Days of the New Year', videoUrl: '', description: 'Doraemon makes the New Year holiday last forever.' },
                    { episodeNumber: 37, title: 'Big Panic! A Super Baby', videoUrl: '', description: 'A baby accidentally gains superpowers and causes panic.' },
                    { episodeNumber: 38, title: 'Praise Makes an Artist / Which Life Path to Take', videoUrl: '', description: 'A gadget makes anyone a master artist when praised. / Nobita views his future career options.' },
                    { episodeNumber: 39, title: 'Sensitivity-to-Cold Correcting Band / Too Effective!', videoUrl: '', description: 'A headband that cures sensitivity to cold. / A medicinal gadget works too well.' },
                    { episodeNumber: 40, title: 'Gorgeous! Suneo’s Poverty Birthday', videoUrl: '', description: 'Suneo experiences what it is like to be poor for his birthday.' },
                    { episodeNumber: 41, title: 'Slippery! Teacher Can’t Stop / Millionaire Nobita', videoUrl: '', description: 'Making the teacher slip everywhere. / Nobita uses a gadget to become rich.' },
                    { episodeNumber: 42, title: 'Exteriorize Mirror / Moving with Flat Roller', videoUrl: '', description: 'A mirror that shows your inner thoughts. / Using rollers to move heavy objects easily.' },
                    { episodeNumber: 43, title: 'Nobita’s Field Trip Survival', videoUrl: '', description: 'Nobita prepares survival skills for an upcoming school trip.' },
                    { episodeNumber: 44, title: 'A Long Skinny Friend / The Laughing Doll Curse', videoUrl: '', description: 'Nobita befriends a snake? / A cursed doll forces everyone to laugh.' },
                    { episodeNumber: 45, title: 'Mom was Nobita in the Past!', videoUrl: '', description: 'Nobita visits the past and sees that his mom was just like him.' },
                    { episodeNumber: 46, title: 'Create a Weakness for Gian and Dekisugi', videoUrl: '', description: 'Nobita tries to invent weaknesses for his perfect rivals.' },
                    { episodeNumber: 47, title: 'Shizuka and the Grandpa Tree', videoUrl: '', description: 'Shizuka fights to save an ancient tree from being cut down.' },
                    { episodeNumber: 48, title: 'The Opposite – The Nobita that Nobita Didn’t Know', videoUrl: '', description: 'Nobita meets a mirror-version of himself with opposite traits.' },
                    { episodeNumber: 49, title: 'Where Did Cinderella Go', videoUrl: '', description: 'Cinderella vanishes from her storybook, and they must find her.' },
                    { episodeNumber: 50, title: 'Dreaming of Grandpa', videoUrl: '', description: 'Nobita visits his late grandfather within a dream.' },
                    { episodeNumber: 51, title: 'I’m Doraemon Hosokawa / Let’s Drive in a Vacuum Cleaner', videoUrl: '', description: 'A famous actor seems to be Doraemon? / Shrinking down to drive a vacuum cleaner.' },
                    { episodeNumber: 52, title: 'Catching Umibozu! / The House Becomes a Robot', videoUrl: '', description: 'Hunting for a legendary sea monster. / The Nobi house transforms into a giant robot.' }
                ]
            },
            {
                seasonNumber: 16,
                title: "Season 16",
                episodes: [
                    { episodeNumber: 1, title: 'A Story of Peeling Body Skin / Jaiko and Dorami Have Boyfriends', videoUrl: '', description: 'Snakes shed their skin, but can humans? / Rumors fly about the sisters having boyfriends.' },
                    { episodeNumber: 2, title: 'Welcome to the Haunted Inn', videoUrl: '', description: 'The gang stays at an inn that turns out to be spookier than expected.' },
                    { episodeNumber: 3, title: 'Nobita’s Birthday Adventure', videoUrl: '', description: 'Doraemon sets up a special adventure to celebrate Nobita\'s birthday.' },
                    { episodeNumber: 4, title: 'Everybody Changing Bodies / Dunking Powder', videoUrl: '', description: 'A gadget causes everyone in town to swap bodies. / Powder that lets you pass through solid objects.' },
                    { episodeNumber: 5, title: 'Treasure of Skull Island', videoUrl: '', description: 'Nobita and friends go hunting for pirate treasure on a skull-shaped island.' },
                    { episodeNumber: 6, title: 'Transform Transform and Transform Again / The Little House on the Big Ice Mountain', videoUrl: '', description: 'Constant shapeshifting fun. / Building a cozy house on a freezing iceberg.' },
                    { episodeNumber: 7, title: 'Flying to the Sky with the Character Wa / Transform! The Dracula Set', videoUrl: '', description: 'Flying using giant katakana characters. / Nobita uses a vampire costume kit.' },
                    { episodeNumber: 8, title: 'A Genuine 3-D Television / On That Day Everything Became Mice', videoUrl: '', description: 'A TV where things physically come out of the screen. / A world where people turn into mice.' },
                    { episodeNumber: 9, title: 'The Land of Sweets', videoUrl: '', description: 'Visiting a magical kingdom made entirely of candy and pastries.' },
                    { episodeNumber: 10, title: 'Puppy Ichi’s Country Forging a Bond', videoUrl: '', description: 'Nobita\'s stray dog Ichi travels to the past and builds a civilization.' },
                    { episodeNumber: 11, title: 'Puppu Ichi’s Country Hope', videoUrl: '', description: 'The emotional conclusion of Ichi\'s story and his bond with Nobita.' },
                    { episodeNumber: 12, title: 'Doraemon Wants a Mother Too / Let’s Go to a Spa with Shizuka', videoUrl: '', description: 'Doraemon creates a robot mother. / A relaxing trip to a hot spring spa.' },
                    { episodeNumber: 13, title: 'Cat’s Cradle World Champion', videoUrl: '', description: 'Nobita uses a gadget to become a world-renowned champion at string figures.' },
                    { episodeNumber: 14, title: 'Jaiko’s Scary Curry / One Up One Back', videoUrl: '', description: 'Jaiko cooks a terrifyingly spicy curry. / A gadget that moves you one step forward, one back.' },
                    { episodeNumber: 15, title: 'Giant Radish Dance Party', videoUrl: '', description: 'Giant radishes come to life and have a dance party.' },
                    { episodeNumber: 16, title: 'Nobita’s Pet is a Paper Dog', videoUrl: '', description: 'Nobita creates a dog out of paper that comes to life.' },
                    { episodeNumber: 17, title: 'There’s Snow in Nobita’s Neighborhood', videoUrl: '', description: 'Using a gadget to make it snow only around Nobita\'s block.' },
                    { episodeNumber: 18, title: 'Renovating Gian’s House / The Nobita Sticker', videoUrl: '', description: 'Fixing up Gian\'s shop. / Stickers that make anyone act like Nobita.' },
                    { episodeNumber: 19, title: 'Running Away to the Cretaceous Period', videoUrl: '', description: 'Nobita runs away from home to the age of dinosaurs.' },
                    { episodeNumber: 20, title: 'Cast Your Vote for Boss! / Rigid Doraemon', videoUrl: '', description: 'Holding an election for the group leader. / Doraemon becomes incredibly stiff.' },
                    { episodeNumber: 21, title: 'Nobita’s Chaotic First Day of School', videoUrl: '', description: 'Nobita travels back to relieve his disastrous first day of elementary school.' },
                    { episodeNumber: 22, title: 'Welcome to Nobi Hotel! / Just Stay Honest!', videoUrl: '', description: 'Turning the Nobi house into a hotel. / A doll that forces you to speak the truth.' },
                    { episodeNumber: 23, title: 'Not This Kind of Shizuka!', videoUrl: '', description: 'A gadget causes Shizuka to act completely out of character.' },
                    { episodeNumber: 24, title: 'The Lost and Found Fishing Pond / Thankfulness Device', videoUrl: '', description: 'Fishing for lost items in a pond. / A machine that demands gratitude for every action.' },
                    { episodeNumber: 25, title: 'Troublesome Gulliver / Nobita the Talk of the Town', videoUrl: '', description: 'A tiny alien visits Nobita. / A gadget makes Nobita famous for a day.' },
                    { episodeNumber: 26, title: 'Otter Nobita’s Big Adventure', videoUrl: '', description: 'Nobita transforms into an otter for a river adventure.' },
                    { episodeNumber: 27, title: 'The Big Popularity Plan / Wishing a Star', videoUrl: '', description: 'Nobita tries to become the most popular kid. / A gadget that catches falling stars.' },
                    { episodeNumber: 28, title: 'Debut Song! Gian’s An Amazing Singer', videoUrl: '', description: 'Has Gian finally learned to sing well, or is it a gadget?' },
                    { episodeNumber: 29, title: 'Shizuka Does an Oppekepe / Nobita Can Stop Himself', videoUrl: '', description: 'Shizuka acts silly due to a gadget. / Nobita finally gains some self-control.' },
                    { episodeNumber: 30, title: 'Memories of Grandma', videoUrl: '', description: 'Nobita travels back in time to share a moment with his beloved grandmother.' },
                    { episodeNumber: 31, title: 'The Star Festival Sky Came Falling', videoUrl: '', description: 'A gadget causes the starry night sky to descend to Earth.' },
                    { episodeNumber: 32, title: 'The Spare Pocket / The Giant Sashimi', videoUrl: '', description: 'Doraemon\'s spare pocket goes missing. / Creating a giant slice of sashimi.' },
                    { episodeNumber: 33, title: 'The Night Train / Riding to School on a Cloud', videoUrl: '', description: 'A magical train that runs through the night. / Riding clouds to avoid traffic.' },
                    { episodeNumber: 34, title: 'The Dekisugi Incident / Ultra Ring', videoUrl: '', description: 'A mysterious phone call from Dekisugi. / A ring that grants super strength.' },
                    { episodeNumber: 35, title: 'Nobita Becomes a Ghost / The Puddle Pirarucu', videoUrl: '', description: 'Nobita turns into a ghost to scare people. / Fishing for giant Amazonian fish in a puddle.' },
                    { episodeNumber: 36, title: 'The Gian Battery is Infinite / The Cute Stone 2', videoUrl: '', description: 'Harnessing Gian\'s rage as an energy source. / A stone that makes anything cute.' },
                    { episodeNumber: 37, title: 'Gian Appears on TV! / A Story Badge for a Hot Summer', videoUrl: '', description: 'Gian tries to get on television. / Badges that create exciting summer stories.' },
                    { episodeNumber: 38, title: 'Real-Lie-zer / What’s Mine Is Yours', videoUrl: '', description: 'A gadget that turns lies into reality. / Imposing Gian\'s selfish philosophy on everyone.' },
                    { episodeNumber: 39, title: 'Doraemon’s One-Day Love Affair', videoUrl: '', description: 'Doraemon falls in love with a cat toy for 24 hours.' },
                    { episodeNumber: 40, title: 'I’m Taking the Good Parts About You / King Nobita', videoUrl: '', description: 'Stealing people\'s best traits. / Nobita becomes a king of his own kingdom.' },
                    { episodeNumber: 41, title: 'Run Umatake / The Light of the Moon', videoUrl: '', description: 'Racing on bamboo stilts that run. / Does moonlight provide energy?' },
                    { episodeNumber: 42, title: 'The Genie-less Magic Lamp / Nobita’s Ninja Training', videoUrl: '', description: 'A magic lamp that works without a genie. / Nobita undergoes ninja training.' },
                    { episodeNumber: 43, title: 'The It Shall Be Set / The Best! Worst Meal Service', videoUrl: '', description: 'A gadget that forces events to happen. / A delivery service that is hit or miss.' },
                    { episodeNumber: 44, title: 'Super Mobile Bath 1010 / Nobita Becomes Company President', videoUrl: '', description: 'A bath that can fly anywhere. / Nobita starts his own company.' },
                    { episodeNumber: 45, title: 'Mechanical Transformation Device / Only Yours Gas', videoUrl: '', description: 'Turning people into machines. / Gas that marks items as your property.' },
                    { episodeNumber: 46, title: 'I’m Nobiko / Mecha Maker', videoUrl: '', description: 'Nobita transforms into a girl named Nobiko. / A device to create custom mechs.' },
                    { episodeNumber: 47, title: 'Young Master Mambo / Lying Mirror', videoUrl: '', description: 'A dancing gadget. / A mirror that flatters you with lies.' },
                    { episodeNumber: 48, title: 'Jumbo Suneo Appears! / Nap Championship', videoUrl: '', description: 'Suneo grows to giant size. / Nobita competes in a sleeping contest.' },
                    { episodeNumber: 49, title: 'Anywhere Cannon / Gravity Paint', videoUrl: '', description: 'A cannon that fires you to your destination. / Paint that allows walking on walls.' },
                    { episodeNumber: 50, title: 'Send the Rude Caller Home / Memorization Bread for Tests', videoUrl: '', description: 'Getting rid of unwanted guests. / Eating bread to memorize test answers.' },
                    { episodeNumber: 51, title: 'Quiz Takes You Around the World / Attic Bell Pepper Patch', videoUrl: '', description: 'A quiz game that transports you globally. / Growing vegetables in the attic.' },
                    { episodeNumber: 52, title: 'The Happy Toasty Sticker / Mom vs Mom Battle', videoUrl: '', description: 'Stickers that produce warmth. / Nobita\'s mom competes with Suneo\'s mom.' }
                ]
            },
            {
                seasonNumber: 17,
                title: "Season 17",
                episodes: [
                    { episodeNumber: 1, title: 'Ultra Mixer / Sneeze Busters!', videoUrl: '', description: 'A gadget can combine any two items into one. / Battling monsters created from sneezes?' },
                    { episodeNumber: 2, title: 'Demons In! Luck In! Bean / Good-Bye Shizuka Part II', videoUrl: '', description: 'Using special beans for the Setsubun festival. / Nobita tries to push Shizuka away for her own good.' },
                    { episodeNumber: 3, title: 'Gian’s Stew / Animal Training Shop Opens!', videoUrl: '', description: 'Gian cooks his horrific "special" stew for everyone. / Nobita opens a business to train pets.' },
                    { episodeNumber: 4, title: 'A Warm Snow Fight / Suneo Works At the Goda Family', videoUrl: '', description: 'Enjoying a snowball fight with warming gadgets. / Suneo is forced to work at Gian\'s store.' },
                    { episodeNumber: 5, title: 'We Started a TV Station / Freeze', videoUrl: '', description: 'The gang launches their own television channel. / A gadget that can freeze time or people.' },
                    { episodeNumber: 6, title: 'Devotion Horsetail / Delay Candy', videoUrl: '', description: 'A plant that makes people loyal to you. / Candy that delays sound so you hear it later.' },
                    { episodeNumber: 7, title: 'Let’s Enjoy Life / Nobita’s Son Has Run Away From Home', videoUrl: '', description: 'A gadget to make life more exciting. / Nobita\'s rebellious son from the future visits.' },
                    { episodeNumber: 8, title: 'Delicious Hot Spring Bathing / Treasure Hunting Kit', videoUrl: '', description: 'Creating instant hot springs at home. / Using a kit to find buried treasure.' },
                    { episodeNumber: 9, title: 'Doraemon’s 100 Year Time Capsule', videoUrl: '', description: 'Doraemon buries a time capsule to be opened 100 years in the future.' },
                    { episodeNumber: 10, title: 'A Golden Week Sheltered from People / The Apartment Tree', videoUrl: '', description: 'Escaping the holiday crowds. / Growing a fully functional apartment building from a tree.' },
                    { episodeNumber: 11, title: 'Fake Aliens / Doron Leaf', videoUrl: '', description: 'Staging a fake alien invasion. / A leaf that allows for magical transformations.' },
                    { episodeNumber: 12, title: 'Let’s Watch the Solar Eclipse / Jaiko the Comic Artist', videoUrl: '', description: 'The town gathers to view a solar eclipse. / Jaiko seeks inspiration for her next manga.' },
                    { episodeNumber: 13, title: 'This Road That Road and the Easy Road / Shizuka in My Pocket', videoUrl: '', description: 'A gadget predicts the outcome of different paths. / shrinking Shizuka to keep her safe?' },
                    { episodeNumber: 14, title: 'A Visit to Jaiko’s Comic / The Weather Box', videoUrl: '', description: 'Entering the world inside Jaiko\'s manga. / A box that allows control over the local weather.' },
                    { episodeNumber: 15, title: 'I’ll Eat Candy and Become a Singer 2 / Go Back Light', videoUrl: '', description: 'Candy that transforms your voice. / A light that reverts objects to their previous state.' },
                    { episodeNumber: 16, title: 'The Chance Maker / Happy Promenade', videoUrl: '', description: 'A gadget that creates opportunities. / A walking path that makes everyone happy.' },
                    { episodeNumber: 17, title: 'The Look Alike Bean Jelly / Forgotten Item Delivery Machine', videoUrl: '', description: 'Food that makes you look like whoever gave it to you. / retrieving forgotten items instantly.' },
                    { episodeNumber: 18, title: 'Bug-bug Hero On the Scene! / One-Inch Boy', videoUrl: '', description: 'Nobita becomes a superhero for insects. / The gang enacts the story of Issun-boshi.' },
                    { episodeNumber: 19, title: 'Nobita’s Room is Off Limits / Have no fear! Gian’s Insurance Plan', videoUrl: '', description: 'Securing Nobita\'s room from intruders. / Gian starts a dubious insurance business.' },
                    { episodeNumber: 20, title: 'Showdown! Gian vs The Monster Army / World Record Rock', videoUrl: '', description: 'Gian fights an army of monsters. / A rock that allows you to break any world record.' },
                    { episodeNumber: 21, title: 'Charge! Submarine Nobita / Job Hunting is Fun', videoUrl: '', description: 'Exploring the underwater world in a sub. / A simulator for experiencing different careers.' },
                    { episodeNumber: 22, title: 'Can’t Quit the Life of a Ghost / How to Get a Response', videoUrl: '', description: 'Nobita finds being a ghost addictive. / A gadget that forces people to answer you.' },
                    { episodeNumber: 23, title: 'Go Flowing Noodles! / Ten Minute Delay Psychic Powers', videoUrl: '', description: 'A high-speed flowing noodles party. / Psychic powers that only take effect after 10 minutes.' },
                    { episodeNumber: 24, title: 'Big Adventure Game Book / Incident Bomb', videoUrl: '', description: 'Entering the world of a game book. / A time bomb that causes random incidents.' },
                    { episodeNumber: 25, title: 'Flying Fish / Play Favorite Tree Badge', videoUrl: '', description: 'Making fish fly through the air. / A badge that makes trees protect you.' },
                    { episodeNumber: 26, title: 'Werewolf Cream 2 / Human Time Switch', videoUrl: '', description: 'Cream that transforms you into a wolf. / A switch to fast-forward through boring times.' },
                    { episodeNumber: 27, title: 'Nobita Wins with a Cucumber / Extension Spray', videoUrl: '', description: 'Nobita wins a contest using a cucumber? / Spray that extends the reach of your hands.' },
                    { episodeNumber: 28, title: 'Sensational Duo Jai & Sune / Horror of Happy Playing Cards', videoUrl: '', description: 'Gian and Suneo form a pop duo. / Cards that grant luck but collect a debt later.' },
                    { episodeNumber: 29, title: 'Great Performance Clapperboard / Sloth Suit', videoUrl: '', description: 'Turning everyday life into a movie scene. / A suit that forces the wearer to be lazy.' },
                    { episodeNumber: 30, title: 'Discipline Candy / The Horn of Hamelin', videoUrl: '', description: 'Candy that forces good behavior. / A magical horn that controls living things.' },
                    { episodeNumber: 31, title: 'River Swimming with Sake / Auto Revenge Radar', videoUrl: '', description: 'Swimming in a river of juice/sake? / A radar that helps you exact revenge.' },
                    { episodeNumber: 32, title: 'Let’s All Dance Shoes / The Tanuki that Fell in Love', videoUrl: '', description: 'Shoes that force you to dance. / A raccoon dog falls in love with Doraemon.' },
                    { episodeNumber: 33, title: 'The Dreadful Gian Pizza / Let’s Form a Band! No-Beatles!', videoUrl: '', description: 'Gian tries to make pizza. / The gang forms a band called the "No-Beatles".' },
                    { episodeNumber: 34, title: 'Human Piggy Bank / Super Detective Nobita is Born!', videoUrl: '', description: 'A gadget that turns people into banks. / Nobita becomes a brilliant detective.' },
                    { episodeNumber: 35, title: 'I Want to Eat Crab! / Shopping in a Different Era', videoUrl: '', description: 'The hunt for expensive crab meat. / Traveling to the past to find cheaper goods.' },
                    { episodeNumber: 36, title: 'Ultra Good Fortune Sushi Roll / The Snow is Burning Hot', videoUrl: '', description: 'Sushi that grants extreme luck. / A gadget that makes snow feel hot.' },
                    { episodeNumber: 37, title: 'Love at First Sight / Shizuka’s Space Outdoor', videoUrl: '', description: 'A gadget that induces instant love. / Going camping in outer space.' },
                    { episodeNumber: 38, title: 'Phantom Thief / Take to the Sky in Bird Caps', videoUrl: '', description: 'Nobita becomes a phantom thief? / Hats that allow you to fly like birds.' },
                    { episodeNumber: 39, title: 'Mom and Dad Battle It Out / The Always-Accurate Palmistry', videoUrl: '', description: 'Nobita\'s parents have a big fight. / A palm reading manual that is never wrong.' },
                    { episodeNumber: 40, title: 'Explosive Pepper / Flower Viewing or Bust', videoUrl: '', description: 'Pepper that causes explosive sneezes. / The race to find a spot for cherry blossom viewing.' },
                    { episodeNumber: 41, title: 'Budgeting for a Trip to Hawaii / Shizuka’s Magic Cloak', videoUrl: '', description: 'The family tries to save for a vacation. / A cloak that performs magic tricks.' },
                    { episodeNumber: 42, title: 'Napping in Heaven / Dictator Switch', videoUrl: '', description: 'Finding the perfect nap spot in the clouds. / The terrifying button that erases people.' },
                    { episodeNumber: 43, title: 'Instant Mom / Gian is Being Targeted', videoUrl: '', description: 'Creating a temporary substitute mom. / Someone is plotting against Gian.' },
                    { episodeNumber: 44, title: 'Escape! The Honekawa House of Terror / Helmet of Telepathy', videoUrl: '', description: 'Suneo\'s house turns into a haunted attraction. / A helmet that reads minds.' },
                    { episodeNumber: 45, title: 'House Kopter / Shizuka’s Terrible Birthday', videoUrl: '', description: 'Moving the entire house with a propeller. / Shizuka has a disastrous birthday.' },
                    { episodeNumber: 46, title: 'Vermilion Mixing Stick / Gian Becomes a Panda', videoUrl: '', description: 'A stick that mixes properties of objects. / Gian accidentally turns into a panda.' },
                    { episodeNumber: 47, title: 'Gifting Cloth / Invincible! Black Belt Nobita', videoUrl: '', description: 'A cloth that produces gifts. / Nobita uses a gadget to become a judo master.' },
                    { episodeNumber: 48, title: 'Gian’s Farewell Concert / Dream Director’s Chair', videoUrl: '', description: 'Is Gian really retiring from singing? / Manipulating people\'s dreams.' },
                    { episodeNumber: 49, title: 'Reverse World Mirror / Nobita’s Secret Tunnel', videoUrl: '', description: 'Entering the world inside the mirror. / Nobita digs a secret tunnel to freedom.' },
                    { episodeNumber: 50, title: 'The Remap Map / Mirrormercials', videoUrl: '', description: 'Redesigning the town map. / Advertisements appearing in mirrors.' },
                    { episodeNumber: 51, title: 'Anything Ice Cream Sticks / Resolve Makes a Man!', videoUrl: '', description: 'Molding any object into ice cream. / A gadget that helps build determination.' },
                    { episodeNumber: 52, title: 'Deep-Sea Cycling / Nobita’s Candid Video', videoUrl: '', description: 'Riding bicycles on the ocean floor. / Nobita gets secretly filmed.' }
                ]
            },
            {
                seasonNumber: 18,
                title: "Season 18",
                episodes: [
                    { episodeNumber: 1, title: 'Let\'s Grow Fireworks! / Dividing Hammer', videoUrl: 'https://www.facebook.com/reel/1383855083485146/', description: 'Nobita and Doraemon grow their own fireworks and use a dividing hammer.' },
                    { episodeNumber: 2, title: 'Spending Summer Break with Monsters / Shine Solidifier', videoUrl: 'https://www.facebook.com/reel/1577471786992732/', description: 'A summer adventure with monsters and a gadget that solidifies light.' },
                    { episodeNumber: 3, title: 'Nobita\'s Big Summer Festival Plan! / I Can\'t Study in the Sahara Desert', videoUrl: 'https://www.facebook.com/reel/1050024773945461/', description: 'Planning a summer festival and an unexpected trip to the Sahara.' },
                    { episodeNumber: 4, title: 'Nobita\'s Energy Usage / Fly the Nosebubbles', videoUrl: 'https://www.facebook.com/reel/1275646047731267/', description: 'Nobita learns about energy and flies with nose bubbles.' },
                    { episodeNumber: 5, title: 'Human Locomotive / Mushroom-gathering in the Miniscape', videoUrl: 'https://www.facebook.com/reel/910080471369814/', description: 'Becoming a human locomotive and gathering mushrooms in a miniature world.' },
                    { episodeNumber: 6, title: 'What is Halloween / Tasting Spoon', videoUrl: 'https://www.facebook.com/reel/1573184317322799/', description: 'Discovering Halloween traditions and using a magical tasting spoon.' },
                    { episodeNumber: 7, title: 'Go Wild with Magical Hand / Medusa Head', videoUrl: 'https://www.facebook.com/reel/1188634630145844/', description: 'Using a magical hand and encountering Medusa\'s head.' },
                    { episodeNumber: 8, title: 'The Feelings of a Roasted Sweet Potato / A Dazzling Comet', videoUrl: 'https://www.facebook.com/reel/870682702239086/', description: 'Experiencing the emotions of food and witnessing a comet.' },
                    { episodeNumber: 9, title: 'Nobita vs Musashi / Just Before the Battle of Ganryu', videoUrl: 'https://www.facebook.com/reel/26011643261763191/', description: 'Nobita faces off against the legendary samurai Musashi.' },
                    { episodeNumber: 10, title: 'Fur Ring / Sparkling Christmas Strategy', videoUrl: 'https://www.facebook.com/reel/695750903597213/', description: 'A magical fur ring and planning the perfect Christmas.' },
                    { episodeNumber: 11, title: 'Good House Bad House / Phobia', videoUrl: 'https://www.facebook.com/reel/1201248398177039/', description: 'Exploring different houses and confronting fears.' },
                    { episodeNumber: 12, title: 'Plan for Getting Out of the Earth / Word Restriction Pen', videoUrl: 'https://www.facebook.com/reel/1598955008126931/', description: 'Planning an escape from Earth and using a word restriction pen.' },
                    { episodeNumber: 13, title: 'Animal Payback / Drops Snowman in the Town', videoUrl: 'https://www.facebook.com/reel/803149839408179/', description: 'Animals get their revenge and a snowman appears in town.' },
                    { episodeNumber: 14, title: 'Bon Appétit Chocolate / Nobita Recital at the Blue Moon Night', videoUrl: 'https://www.facebook.com/reel/718903707679735/', description: 'Magical chocolate and a special recital under the blue moon.' },
                    { episodeNumber: 15, title: 'Sushi Conveyor Belt for Humans / Let\'s Have an Easy Life with a Copybrain', videoUrl: 'https://www.facebook.com/reel/1181508277491450/', description: 'Humans on a sushi conveyor belt and using a copybrain gadget.' },
                    { episodeNumber: 16, title: 'Rich Dad Poor Dad / Walking to the Moon!', videoUrl: 'https://www.facebook.com/reel/1553637390098687/', description: 'Experiencing different lifestyles and walking to the moon.' },
                    { episodeNumber: 17, title: 'Skyhorse Farm / Overnight Cramming Barrel', videoUrl: 'https://www.facebook.com/reel/1662071938099135/', description: 'Running a skyhorse farm and cramming for exams overnight.' },
                    { episodeNumber: 18, title: 'Dolphin in the Empty Lot / Blow Out the Obstacles with Time Pistol', videoUrl: 'https://www.facebook.com/reel/867370392701215/', description: 'A dolphin appears in an empty lot and using a time pistol.' },
                    { episodeNumber: 19, title: 'Becoming a King in the Stone Age / Catch the Carp Streamer!', videoUrl: 'https://www.facebook.com/reel/1083850853834283/', description: 'Traveling to the Stone Age and catching carp streamers.' },
                    { episodeNumber: 20, title: 'Let\'s Make an Anywhere Door! / Stork Pay Me Back!', videoUrl: 'https://www.facebook.com/reel/863465886296968/', description: 'Creating an anywhere door and dealing with a stork.' },
                    { episodeNumber: 21, title: 'Nobita Railway / Transforming from a Bag into a River Horse with Transmogrify Ray', videoUrl: 'https://www.facebook.com/reel/1121334626617075/', description: 'Building a railway and transforming objects with a ray.' },
                    { episodeNumber: 22, title: 'What a Surprise! Nobita Scored 100 Percent!!!! / Treasure Hunting in the Chinkara Pass', videoUrl: 'https://www.facebook.com/reel/824397527222072/', description: 'Nobita gets a perfect score and goes treasure hunting.' },
                    { episodeNumber: 23, title: 'Deluxifier / Nobita\'s 100 Score Gets a Big Disaster 25 Years Later', videoUrl: 'https://www.facebook.com/reel/882029907669191/', description: 'Making things deluxe and seeing the future consequences.' },
                    { episodeNumber: 24, title: 'Nobita\'s Fried Shrimp / Help! Helping Boat', videoUrl: 'https://www.facebook.com/reel/1962059357990347/', description: 'Nobita\'s favorite food and a helpful boat gadget.' },
                    { episodeNumber: 25, title: 'Spoiled Dad / Shizuka Turns into a Kappa!', videoUrl: 'https://www.facebook.com/reel/1209428643988559/', description: 'Nobita\'s dad gets spoiled and Shizuka transforms into a kappa.' },
                    { episodeNumber: 26, title: 'Nobita Eleven / The Bartering Machine', videoUrl: 'https://www.facebook.com/reel/2327821277631184/', description: 'Forming a soccer team and using a bartering machine.' },
                    { episodeNumber: 27, title: 'Doraemon\'s Palace Behind Hill / The "Truth Banner" is Always Correct', videoUrl: 'https://www.facebook.com/reel/1838938640159002/', description: 'Doraemon builds a castle in the back hills. / A flag that makes whatever is written on it become the absolute truth.' },
                    { episodeNumber: 28, title: 'Transforming Fish into a Boat / Viral Marketing Virus', videoUrl: 'https://www.facebook.com/reel/1487430635691161/', description: 'Turning fish into boats and dealing with a viral marketing virus.' },
                    { episodeNumber: 29, title: 'Unturned Stone Cap / Nobita\'s Bride', videoUrl: 'https://www.facebook.com/reel/4212836525650479/', description: 'Using an unturned stone cap and seeing Nobita\'s future bride.' },
                    { episodeNumber: 30, title: 'Live Through Summer in a Mini House / Feel-Good Float', videoUrl: 'https://www.facebook.com/reel/1206554237625709/', description: 'Spending summer in a miniature house and using a feel-good float.' },
                    { episodeNumber: 31, title: 'Guiding Angel / Welcome to Notiba Airline', videoUrl: 'https://www.facebook.com/reel/1328890872372452/', description: 'Meeting a guiding angel and starting an airline.' },
                    { episodeNumber: 32, title: 'God Player / Wonderful Camping in the 22nd Century', videoUrl: 'https://www.facebook.com/reel/1360933239103558/', description: 'Becoming a god player and camping in the future.' },
                    { episodeNumber: 33, title: 'Portable Parliament / Popcorn of Anger', videoUrl: 'https://www.facebook.com/reel/1580500500035890/', description: 'Using a portable parliament and magical anger popcorn.' },
                    { episodeNumber: 34, title: 'Trick-or-Tanuki / Wild Pumpkin at Halloween', videoUrl: 'https://www.facebook.com/reel/1684168745894024/', description: 'Halloween tricks with tanuki and wild pumpkins.' },
                    { episodeNumber: 35, title: 'Boasted Ancestor / Flying Manga', videoUrl: 'https://www.facebook.com/reel/1584055495973863/', description: 'Meeting a boastful ancestor and manga that comes to life.' },
                    { episodeNumber: 36, title: 'Let\'s Accuse One Falsely! / Macho Body Clay!', videoUrl: 'https://www.facebook.com/reel/2051344838960647/', description: 'False accusations and using macho body clay.' },
                    { episodeNumber: 37, title: 'Clean Up with the Storm! / Fallen Leaves and Jaiko', videoUrl: 'https://www.facebook.com/reel/25756916053940059/', description: 'Cleaning with a storm and autumn adventures with Jaiko.' },
                    { episodeNumber: 38, title: 'Nobita Became Shizuka / Clone Juice', videoUrl: 'https://www.facebook.com/reel/4112660922379482/', description: 'Nobita transforms into Shizuka and uses clone juice.' },
                    { episodeNumber: 39, title: 'Money is Worthless in This World / Dorami\'s Birthday', videoUrl: 'https://www.facebook.com/reel/1980651385813701/', description: 'A world without money and celebrating Dorami\'s birthday.' },
                    { episodeNumber: 40, title: 'Recycling with the Make-do Ant / Sweetstick', videoUrl: 'https://www.facebook.com/reel/856627560492873/', description: 'Recycling with helpful ants and using a sweetstick.' },
                    { episodeNumber: 41, title: 'The Master Board / The City Covered with Silly Pepper', videoUrl: 'https://www.facebook.com/reel/1668496891265053/', description: 'Using a master board and a city covered in silly pepper.' },
                    { episodeNumber: 42, title: 'Let\'s Become a Snow Fairy / Protect the World in the Secret Base!', videoUrl: 'https://www.facebook.com/reel/4430654517163927/', description: 'Becoming a snow fairy and protecting the world from a secret base.' },
                    { episodeNumber: 43, title: 'Four-dimensional Cycling / Rice Cake and Sumo for Valentine\'s Day', videoUrl: 'https://www.facebook.com/reel/1459146875543848/', description: 'Cycling through dimensions and Valentine\'s Day sumo.' },
                    { episodeNumber: 44, title: 'Dinosaur Hunter', videoUrl: 'https://www.facebook.com/reel/1530456094908732/', description: 'Going on a thrilling dinosaur hunting adventure.' },
                    { episodeNumber: 45, title: 'Skiing in the Miniscape Set with Shizuka / The Richer Boy than Suneo', videoUrl: 'https://www.facebook.com/reel/1957134448565347/', description: 'Skiing in a miniature world and meeting someone richer than Suneo.' },
                    { episodeNumber: 46, title: 'Pet Look-Alike Pie / Invincible Super Backpack', videoUrl: 'https://www.facebook.com/reel/2097468171082769/', description: 'Creating pet look-alikes and using an invincible backpack.' },
                    { episodeNumber: 47, title: 'Dive into the Clam Pack! / Let\'s Punish Intercepting Gian', videoUrl: 'https://www.facebook.com/reel/25994918706772022/', description: 'Diving into a clam pack and teaching Gian a lesson.' },
                    { episodeNumber: 48, title: 'Nobita\'s Cardboard Space Station / Forget-me-lots', videoUrl: 'https://www.facebook.com/reel/646858691850258/', description: 'Building a space station from cardboard and using forget-me-lots.' },
                    { episodeNumber: 49, title: 'Let\'s Move Here And There / Split the River in Half with the Staff', videoUrl: 'https://www.facebook.com/reel/885997407720384/', description: 'Moving around freely and splitting rivers with a magical staff.' },
                    { episodeNumber: 50, title: 'Revenge Vouchers Voyage on a Dolphin', videoUrl: 'https://www.facebook.com/reel/1184198350510653/', description: 'Using revenge vouchers and voyaging on a dolphin.' },
                    { episodeNumber: 51, title: 'Sweetbot Gian Comes Flying', videoUrl: 'https://www.facebook.com/reel/2147068752774134/', description: 'Gian becomes a sweet robot and takes to the skies.' },
                    { episodeNumber: 52, title: 'Our Great Battle in the Sky Hugga-pills', videoUrl: 'https://www.facebook.com/reel/795259113572718/', description: 'An epic sky battle with the power of hugga-pills.' }
                ]
            }
        ]
    },
    {
        id: 'dragon-ball-super-series',
        type: 'series',
        category: ['tvSeries'],
        title: 'Dragon Ball Super',
        description: 'Six months after the defeat of Majin Buu, The mighty Saiyan Son Goku continues his quest on becoming stronger.',
        imageUrl: 'images/dragon_ball_super_hero.png',
        language: 'Hindi',
        seasons: [
            {
                seasonNumber: 1,
                title: "God of Destruction Beerus Saga",
                episodes: [
                    { episodeNumber: 1, title: 'The Peace Prize', videoUrl: 'https://www.facebook.com/watch/?v=dbs1', description: 'Goku is working as a farmer.' },
                    { episodeNumber: 2, title: 'Vegeta\'s Family Trip', videoUrl: 'https://www.facebook.com/watch/?v=dbs2', description: 'Vegeta takes Trunks and Bulma on vacation.' }
                ]
            }
        ]
    },

    // Doraemon Classics (Titles updated with "Doraemon: ")
    { id: 'doraemon-earth-symphony-2024', type: 'movie', category: ['latestReleases', 'doraemonClassics'], title: "Doraemon the Movie-Nobita's Earth Symphony (2024)", description: "Nobita and friends embark on an adventure to save the world from a future without music. They meet Mikka, a girl from a planet powered by music, and must maintain their harmony to defeat the noise monster.", imageUrl: 'images/doraemon-earth-symphony-hero.png', videoUrl: 'https://www.facebook.com/reel/1218851296812683/', language: 'Hindi dubbed' },
    { id: 'sky-utopia-2023', type: 'movie', category: ['latestReleases', 'doraemonClassics'], title: 'Doraemon: Sky Utopia (2023)', description: 'Nobita and Doraemon embark on a grand adventure for a sky utopia.', imageUrl: 'images/doraemon-sky-utopia.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/3932224157088366/', language: 'Hindi dubbed' },
    { id: 'stand-by-me-2-2020', type: 'movie', category: ['latestReleases', 'doraemonClassics'], title: 'Doraemon: Stand by Me 2 (2021)', description: 'A heartwarming sequel on Nobita\'s journey to his future wedding.', imageUrl: 'images/doraemon-stand-by-me-2.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/4111010009177962/', language: 'Hindi dubbed' },
    { id: 'doraemon-new-dinosaur-2020', type: 'movie', category: ['doraemonClassics', 'latestReleases'], title: "Doraemon the Movie-Nobita's New Dinosaur (2020)", description: "Nobita discovers an egg that hatches two new species of dinosaurs, Kyu and Myu. He raises them with care, but as they grow, he realizes they must return to their own time.", imageUrl: 'images/doraemon-new-dinosaur-2020.png', videoUrl: 'https://www.facebook.com/reel/3868486506616979/', language: 'Hindi dubbed' },
    { id: 'moon-exploration', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Moon Exploration (2019)', description: 'A fantastic journey to the moon awaits.', imageUrl: 'images/doraemon-moon-exploration.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1089875305836794/', language: 'Hindi dubbed' },
    { id: 'treasure-island', type: 'movie', category: ['doraemonClassics'], title: "Doraemon: Nobita's Treasure Island (2018)", description: 'Nobita and Doraemon seek a mysterious treasure island.', imageUrl: 'images/doraemon-treasure-island.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/640454295760593/', language: 'Hindi dubbed' },
    { id: 'antarctic-kachi-kochi', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Antarctic Kachi Kochi (2017)', description: 'A freezing adventure to uncover a hidden city of ice!', imageUrl: 'images/doraemon-antarctic-kachi-kochi.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1723058328351545/', language: 'Hindi dubbed' },
    { id: 'birth-of-japan', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Birth Of Japan (1989)', description: 'Nobita and friends travel to the Stone Age.', imageUrl: 'images/doraemon-birth-of-japan.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1655457565117495/', language: 'Hindi dubbed' },
    { id: 'gadget-museum', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Gadget Museum (2013)', description: 'A thrilling mystery at the secret gadget museum.', imageUrl: 'images/doraemon-gadget-museum.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1470419020634494/', language: 'Hindi dubbed' },
    { id: 'jadooi-tapu', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Nobita Aur Jadooi Tapu (2012)', description: 'Nobita and Doraemon discover a magical island.', imageUrl: 'images/doraemon-jadooi-tapu.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1044495797465981/', language: 'Hindi dubbed' },
    { id: 'steel-troops', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Steel Troops (2011)', description: 'Nobita and Doraemon face a robot invasion to protect Earth.', imageUrl: 'images/doraemon-steel-troops.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1051273367116965/', language: 'Hindi dubbed' },
    { id: 'jalpari', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Jalpari (2010)', description: 'Nobita and Doraemon embark on an underwater quest with a mermaid.', imageUrl: 'images/doraemon-jalpari.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1050964053530942/', language: 'Hindi dubbed' },
    { id: 'hara-hara-planet', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Hara Hara Planet (2008)', description: 'Journey to a dangerous, plant-filled planet.', imageUrl: 'images/doraemon-hara-hara-planet.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/24854423730809045/', language: 'Hindi dubbed' },
    { id: 'toofani-adventure', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Toofani Adventure (2003)', description: 'Doraemon and friends face a storm of challenges.', imageUrl: 'images/doraemon-toofani-adventure.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1677849806264181/', language: 'Hindi dubbed' },
    { id: 'birdopia-sultan', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Birdopia Sultan (2001)', description: 'Doraemon and friends help bird-people against an evil ruler.', imageUrl: 'images/doraemon-birdopia-sultan.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/4061355814138236/', language: 'Hindi dubbed' },
    { id: 'galaxy-super-express', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Galaxy Super Express (1996)', description: 'An exciting space adventure across the universe!', imageUrl: 'images/doraemon-galaxy-super-express.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/182637258357201/', language: 'Hindi dubbed' },
    { id: 'nayi-duniya', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Nobita Ki Nayi Duniya (1995)', description: 'Nobita and Doraemon explore a world of wonders.', imageUrl: 'images/doraemon-nayi-duniya.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/641767961811897/', language: 'Hindi dubbed' },
    { id: 'magical-swordsmen', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Magical Swordsmen (1994)', description: 'Nobita and friends become legendary swordsmen in a dream world.', imageUrl: 'images/doraemon-three-magical-swordsmen.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1805560470314218/', language: 'Hindi dubbed' },
    { id: 'khel-khilona-bhool-bhulaiya', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Nobita Aur Khel Khilona Bhool Bhulaiya (1993)', description: 'Doraemon and Nobita find themselves in a world of toys and must navigate a mysterious and challenging labyrinth.', imageUrl: 'images/doraemon-khel-khilona-bhool-bhulaiya.jpg', videoUrl: 'https://www.facebook.com/reel/1265152048663449/', language: 'Hindi dubbed' },
    { id: 'dorabian-nights', type: 'movie', category: ['doraemonClassics'], title: "Doraemon: Nobita's Dorabian Nights (1991)", description: 'Swept into the magical world of Arabian Nights.', imageUrl: 'images/doraemon-dorabian-nights.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/733719062768636/', language: 'Hindi dubbed' },
    { id: 'animal-planet', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Nobita and the Animal Planet (1990)', description: 'Nobita and his friends travel to a planet of animal-like beings and help them fight against a threat from outer space.', imageUrl: 'images/doraemon-animal-planet.jpg', videoUrl: 'https://www.facebook.com/reel/795227026821012/', language: 'Hindi dubbed' },
    { id: 'little-space-war', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Little Space War (1985)', description: 'Nobita and friends help a tiny alien save his planet.', imageUrl: 'images/doraemon-little-space-war.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1803317223873586/', language: 'Hindi dubbed' },
    { id: 'undersea-devil', type: 'movie', category: ['doraemonClassics'], title: 'Doraemon: Undersea Devil (1983)', description: 'Doraemon and friends explore an ancient underwater castle.', imageUrl: 'images/doraemon-undersea-devil.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/614771978339141/', language: 'Hindi dubbed' },

    // Other Anime Movies
    { id: 'death-note-relight-2007', type: 'movie', category: ['otherAnimeMovies'], title: 'Death Note: Visions of God', description: 'A recap film of the original anime, L\'s perspective.', imageUrl: 'images/death-note-relight.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1266322374949691/', language: 'English' },
    { id: 'dbz-battle-of-gods-2013', type: 'movie', category: ['otherAnimeMovies'], title: 'DBZ: Battle of Gods (2013)', description: 'Goku faces God of Destruction Beerus in a universe-threatening battle.', imageUrl: 'images/dragon-ball-battle-of-gods.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/2608678586139750/', language: 'Hindi' },
    { id: 'db-super-broly-2018', type: 'movie', category: ['otherAnimeMovies'], title: 'DB Super: Broly (2018)', description: 'Goku and Vegeta face formidable Saiyan warrior Broly.', imageUrl: 'images/dragon-ball-super-broly.jpg', videoUrl: 'https://www.facebook.com/nazibul.haque.958129/videos/1272086881027408/', language: 'Hindi' }
];